### ISSUE TITLE
Update the demo sandboxes to run on PHP 8

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/tugboat-demos#2]
PHP 8 has considerable performance improvements over PHP 7, so the assumption is that this will make the sandboxes perform better, so better impression for people testing Backdrop.

**Comment by klonos** [comment]
@BWPanda please see https://github.com/backdrop-ops/tugboat-demos/pull/3

**Comment by ghost** [comment]
Looks good to me. Merged.
